config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :restaurants do
    resources :reservations
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :reservations
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reservations
  has_many :restaurants, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant

  def create
    
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user = current_user

    if @reservation.save
      redirect_to restaurants_url, notice: 'Reservation created successfully'
    else
      render 'restaurants/show'
    end
  end

  def destroy
    @reservation = reservation.find(params[:id])
    @reservation.destroy
  end

  private
  def reservation_params
    params.require(:reservation).permit(:booking_date, :booking_time, :guests_num)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_url
    else
      render :new
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :genre, :capacity, :rating)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to restaurants_url, notice: "Signed Up!"
      else 
        render "new"
      end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :phone)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nice_datetime(datetime)
    datetime.strftime("%A %B #{datetime.day.ordinalize} %Y, %l:%M %p").sub(/(\d)([a-z]+)/, '\1<sup>\2</sup>').html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 


  <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
  <% end %>

<div class="container"> 

  <div class="ui blue inverted menu">
    <a href="/" class="active item">
      <i class="home icon"></i> Home
    </a>
    <a href="/restaurants" class="item">
      <i class="food icon"></i> Restaurants
    </a>
    <a class="item">
      <i class="add icon"></i> Add Restaurant
    </a>
  </div>
</div>
<!--  <div class="ui grid">
/div> -->
<div class="fourteen wide centered column">
<%= yield %>


    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>

  



</body>
</html>

app/views/restaurants/index.html.erb
<h2>All Restaurants</h2>

<% @restaurants.each do |restaurant| %>
<h2><%= link_to restaurant.name, restaurant %></h2>
  <p>

      Category: <%= restaurant.genre %> <br />
      Rating: <div data-rating="5" class="ui star rating">

      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>

    </div>

  </p>




<% end %>

app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>
  <p><%= @restaurant.rating %></p>
  <p><%= @restaurant.genre %></p>
  <p><%= @restaurant.description %></p>

  
<% if current_user %>
  <h4>Make a reservation at <%= @restaurant.name %></h4>
  <%= form_for [@restaurant, @reservation] do |f| %>
    
    <div class="field">
      <%= f.label :booking_date %>
      <%= f.date_select :booking_date %>
    </div><br />
    <div class="field">
      <%= f.label :booking_time %>
      <%= f.select :booking_time, [["1:00", 1],["2:00", 2],["3:00", 3],["4:00", 4],["5:00", 5]] %>
    </div><br />
    <div class="field">
      <%= f.label :guest_num %>
      <%= f.number_field :guests_num, :value => 1, :min => 1 %>
    </div><br />
    <%= f.submit %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %>
  </div>
    <div class="field">
    <%= f.label :phone %><br/>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>